# Generated by Django 6.0 on 2025-12-05 18:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(default='Artist Name', max_length=200)),
                ('content', models.TextField(help_text='Artist biography and life story')),
                ('profile_image', models.ImageField(blank=True, help_text='Optional profile photo of the artist', null=True, upload_to='biography/')),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Biography',
                'verbose_name_plural': 'Biography',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Only letters (a-z, A-Z) and hyphens (-) allowed', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_tag_name', message='Tag names can only contain letters and hyphens', regex='^[a-zA-Z\\-]+$')])),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent tag for hierarchical organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='gallery.tag')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description of the artwork')),
                ('medium', models.CharField(choices=[('watercolour', 'Watercolour'), ('drawing', 'Drawing'), ('photography', 'Photography'), ('other', 'Other')], default='watercolour', help_text='Type of artwork', max_length=20)),
                ('image', models.ImageField(help_text='Upload the artwork image', upload_to='artworks/%Y/%m/')),
                ('year_created', models.IntegerField(blank=True, help_text='Year the artwork was created', null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Display this artwork prominently on the homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, help_text='Select tags to categorize this artwork', related_name='artworks', to='gallery.tag')),
            ],
            options={
                'verbose_name': 'Artwork',
                'verbose_name_plural': 'Artworks',
                'ordering': ['-created_at'],
            },
        ),
    ]
